"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { ARC_THEMES, IDEAL_BUILD_PRESETS, MAIN_ARCS, PRESET_NEGATIVE_ACTIONS, PRESET_POSITIVE_TASKS, STAT_CATEGORIES, STAT_CATEGORY_LABELS } from "@/data/awaken-constants";
import { createPersonalizedStarterState } from "@/hooks/use-awaken-state";
import { defaultOnboardingDraft, DIFFICULTIES, onboardingInputSchema, type OnboardingInput } from "@/lib/onboarding";
import { settingsRepository } from "@/lib/settings-repository";
import type { MainArcId, StatCategory } from "@/types/awaken";

const steps = ["Identity", "Build", "Priorities", "Habits", "Difficulty", "Schedule", "Review"];
const field = "rounded-lg border border-white/15 bg-black/20 p-3 text-white outline-none focus:border-cyan-300";

export default function OnboardingPage() {
  const [draft, setDraft] = useState<OnboardingInput>(defaultOnboardingDraft);
  const draftLoaded = useRef(false);
  const [step, setStep] = useState(0); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [done, setDone] = useState(false);
  useEffect(() => {
    const timer = window.setTimeout(() => {
      const saved = localStorage.getItem("awaken:onboarding-draft:v1");
      if (saved) { try { const parsed = onboardingInputSchema.safeParse(JSON.parse(saved)); if (parsed.success) setDraft(parsed.data); } catch { /* Ignore a damaged local draft. */ } }
      draftLoaded.current = true;
    }, 0);
    return () => window.clearTimeout(timer);
  }, []);
  useEffect(() => { if (draftLoaded.current) localStorage.setItem("awaken:onboarding-draft:v1", JSON.stringify(draft)); }, [draft]);
  const preset = useMemo(() => IDEAL_BUILD_PRESETS.find((item) => item.id === draft.presetId), [draft.presetId]);
  function patch(value: Partial<OnboardingInput>) { setDraft((current) => ({ ...current, ...value })); setError(""); }
  function validate() { if (step === 0 && (!draft.displayName.trim() || !draft.primaryGoal.trim())) return "Display name and primary goal are required."; if (step === 2 && !draft.categories.length) return "Choose at least one life category."; return ""; }
  function next() { const issue = validate(); if (issue) return setError(issue); setStep((value) => Math.min(steps.length - 1, value + 1)); }
  function toggleCategory(category: StatCategory) { const categories = draft.categories.includes(category) ? draft.categories.filter((item) => item !== category) : [...draft.categories, category]; patch({ categories }); }
  function choosePreset(id: string) { const selected = IDEAL_BUILD_PRESETS.find((item) => item.id === id)!; patch({ presetId: id, categories: selected.focusStats, mainArcId: selected.suggestedArcIds[0] }); }
  function toggleTask(id: string, kind: "positive" | "negative") { const source = kind === "positive" ? PRESET_POSITIVE_TASKS.find((x) => x.id === id) : PRESET_NEGATIVE_ACTIONS.find((x) => x.id === id); if (!source) return; const existing = draft.tasks.some((item) => item.id === id); const xp = kind === "positive" ? (source as typeof PRESET_POSITIVE_TASKS[number]).baseXp : (source as typeof PRESET_NEGATIVE_ACTIONS[number]).xpPenalty; patch({ tasks: existing ? draft.tasks.filter((item) => item.id !== id) : [...draft.tasks, { id, title: source.title, kind, stat: source.stat, xp, frequency: "daily", difficulty: "medium" }] }); }
  async function complete() {
    const parsed = onboardingInputSchema.safeParse(draft); if (!parsed.success) return setError(parsed.error.issues[0]?.message ?? "Review your choices.");
    setBusy(true); setError("");
    try {
      const state = createPersonalizedStarterState({ displayName: draft.displayName, mainArcId: draft.mainArcId as MainArcId, arcThemeId: draft.arcThemeId as never, positiveTasks: draft.tasks.filter((x) => x.kind === "positive").map((x) => ({ id: `onboarding-${x.id}`, title: x.title, stat: x.stat, baseXp: x.xp, tags: [x.frequency, x.difficulty] })), negativeActions: draft.tasks.filter((x) => x.kind === "negative").map((x) => ({ id: `onboarding-${x.id}`, title: x.title, stat: x.stat, xpPenalty: x.xp, commonReasons: ["unknown"], tags: [x.frequency, x.difficulty] })) });
      const operationKey = "awaken:onboarding-operation:v1"; let operationId = localStorage.getItem(operationKey); if (!operationId) { operationId = crypto.randomUUID(); localStorage.setItem(operationKey, operationId); }
      await settingsRepository.complete(draft, state, operationId); localStorage.removeItem("awaken:onboarding-draft:v1"); setDone(true); setTimeout(() => window.location.assign("/"), 900);
    } catch (e) { setError(e instanceof Error ? e.message : "Unable to complete onboarding."); } finally { setBusy(false); }
  }
  if (done) return <main className="grid min-h-screen place-items-center bg-[#080b12] p-6 text-white"><section className="text-center"><div className="mx-auto mb-5 grid h-16 w-16 place-items-center rounded-full bg-cyan-300 text-3xl text-slate-950">✓</div><h1 className="text-3xl font-bold">Your system is ready</h1><p className="mt-2 text-slate-400">Entering your personalized dashboard…</p></section></main>;
  return <main className="min-h-screen bg-[#080b12] p-4 text-slate-100 sm:p-8"><section className="mx-auto max-w-4xl"><header className="mb-8"><p className="text-sm font-semibold uppercase tracking-widest text-cyan-300">Awaken setup</p><h1 className="mt-2 text-3xl font-bold">Build a system that fits your life</h1><div className="mt-6 h-2 overflow-hidden rounded bg-white/10"><div className="h-full bg-cyan-300 transition-all" style={{ width: `${((step+1)/steps.length)*100}%` }}/></div><p className="mt-2 text-sm text-slate-400">Step {step+1} of {steps.length}: {steps[step]}</p></header>
    <div className="rounded-2xl border border-white/10 bg-white/[.04] p-5 sm:p-8">
      {step===0 && <div className="grid gap-5"><h2 className="text-2xl font-semibold">Who are you becoming?</h2><label className="grid gap-2">Display name<input className={field} value={draft.displayName} onChange={(e)=>patch({displayName:e.target.value})} autoFocus/></label><label className="grid gap-2">Primary goal<input className={field} value={draft.primaryGoal} onChange={(e)=>patch({primaryGoal:e.target.value})} placeholder="Build strength, launch my business…"/></label><label className="grid gap-2">Why it matters <span className="text-slate-500">(optional)</span><textarea className={field} value={draft.motivation} onChange={(e)=>patch({motivation:e.target.value})}/></label><label className="grid gap-2">Target timeframe <span className="text-slate-500">(optional)</span><input className={field} value={draft.targetTimeframe} onChange={(e)=>patch({targetTimeframe:e.target.value})} placeholder="90 days"/></label></div>}
      {step===1 && <div><h2 className="text-2xl font-semibold">Choose your growth plan</h2><p className="mt-2 text-slate-400"><strong className="text-slate-200">Ideal build</strong> sets your starting mix of focus stats and recommendations. You can customize it now or change it later.</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{IDEAL_BUILD_PRESETS.map((item)=><button key={item.id} onClick={()=>choosePreset(item.id)} className={`rounded-xl border p-4 text-left ${draft.presetId===item.id?'border-cyan-300 bg-cyan-300/10':'border-white/10'}`}><strong>{item.name}</strong><p className="mt-1 text-sm text-slate-400">{item.description}</p><p className="mt-2 text-xs text-cyan-200">Focus: {item.focusStats.map(x=>STAT_CATEGORY_LABELS[x]).join(", ")}</p></button>)}</div><label className="mt-5 grid gap-2"><span>Main arc <small className="block text-slate-400">Your ongoing identity and primary path. The build recommends one, but you remain in control.</small></span><select className={field} value={draft.mainArcId} onChange={(e)=>patch({mainArcId:e.target.value as MainArcId})}>{MAIN_ARCS.map(a=><option key={a.id} value={a.id}>{a.name}{preset?.suggestedArcIds.includes(a.id)?" (recommended)":""} — {a.description}</option>)}</select></label><label className="mt-4 grid gap-2">Visual theme<select className={field} value={draft.arcThemeId} onChange={(e)=>patch({arcThemeId:e.target.value as never})}>{ARC_THEMES.map(x=><option key={x.id} value={x.id}>{x.name} — {x.tagline}</option>)}</select></label></div>}
      {step===2 && <div><h2 className="text-2xl font-semibold">Prioritize your life categories</h2><p className="mt-2 text-slate-400">Select in priority order. Your first choice leads initial recommendations.</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{STAT_CATEGORIES.map((x)=><button key={x} onClick={()=>toggleCategory(x)} className={`rounded-xl border p-4 text-left ${draft.categories.includes(x)?'border-cyan-300 bg-cyan-300/10':'border-white/10'}`}><strong>{draft.categories.indexOf(x)>=0 ? `${draft.categories.indexOf(x)+1}. `:""}{STAT_CATEGORY_LABELS[x]}</strong></button>)}</div></div>}
      {step===3 && <div><h2 className="text-2xl font-semibold">Choose useful habits</h2><p className="mt-2 text-slate-400">XP is shown before you commit. You can add fully custom habits later in Settings.</p><div className="mt-5 grid gap-2">{PRESET_POSITIVE_TASKS.slice(0,6).map(x=><button key={x.id} onClick={()=>toggleTask(x.id,"positive")} className={`flex justify-between rounded-lg border p-3 ${draft.tasks.some(t=>t.id===x.id)?'border-cyan-300':'border-white/10'}`}><span>{x.title}</span><span className="text-cyan-200">+{x.baseXp} XP</span></button>)}{PRESET_NEGATIVE_ACTIONS.slice(0,3).map(x=><button key={x.id} onClick={()=>toggleTask(x.id,"negative")} className={`flex justify-between rounded-lg border p-3 ${draft.tasks.some(t=>t.id===x.id)?'border-amber-300':'border-white/10'}`}><span>{x.title}</span><span className="text-amber-200">−{x.xpPenalty} XP</span></button>)}</div></div>}
      {step===4 && <div><h2 className="text-2xl font-semibold">Set your difficulty</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{Object.entries(DIFFICULTIES).map(([id,x])=><button key={id} onClick={()=>patch({difficulty:id as OnboardingInput['difficulty']})} className={`rounded-xl border p-4 text-left ${draft.difficulty===id?'border-cyan-300 bg-cyan-300/10':'border-white/10'}`}><strong>{x.label}</strong><p className="mt-2 text-sm text-slate-400">{x.xp} · {x.expectations} · {x.penalties}</p></button>)}</div></div>}
      {step===5 && <div className="grid gap-5"><h2 className="text-2xl font-semibold">Schedule and reminders</h2><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2">Daily reset time<input className={field} type="time" value={draft.dailyResetTime} onChange={(e)=>patch({dailyResetTime:e.target.value})}/></label><label className="grid gap-2">Time zone<input className={field} value={draft.timeZone} onChange={(e)=>patch({timeZone:e.target.value})}/></label></div><fieldset><legend>Active days</legend><div className="mt-2 flex flex-wrap gap-2">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((x,i)=><button key={x} onClick={()=>patch({activeDays:draft.activeDays.includes(i)?draft.activeDays.filter(d=>d!==i):[...draft.activeDays,i]})} className={`rounded px-3 py-2 ${draft.activeDays.includes(i)?'bg-cyan-300 text-slate-950':'bg-white/10'}`}>{x}</button>)}</div></fieldset><label className="flex gap-3"><input type="checkbox" checked={draft.remindersEnabled} onChange={(e)=>patch({remindersEnabled:e.target.checked})}/><span>Enable reminders <small className="block text-slate-400">Notification permission will only be requested after you save this choice.</small></span></label>{draft.remindersEnabled&&<label className="grid gap-2">Preferred reminder time<input className={field} type="time" value={draft.reminderTimes[0]??'09:00'} onChange={(e)=>patch({reminderTimes:[e.target.value],reminderTypes:['tasks','daily_review']})}/></label>}</div>}
      {step===6 && <div><h2 className="text-2xl font-semibold">Review your system</h2><dl className="mt-5 grid gap-4 sm:grid-cols-2"><div><dt className="text-slate-500">Identity</dt><dd>{draft.displayName} · {draft.primaryGoal}</dd></div><div><dt className="text-slate-500">Build</dt><dd>{preset?.name} · {MAIN_ARCS.find(x=>x.id===draft.mainArcId)?.name}</dd></div><div><dt className="text-slate-500">Priorities</dt><dd>{draft.categories.map(x=>STAT_CATEGORY_LABELS[x]).join(" → ")}</dd></div><div><dt className="text-slate-500">Difficulty</dt><dd>{DIFFICULTIES[draft.difficulty].label}</dd></div><div><dt className="text-slate-500">Schedule</dt><dd>{draft.dailyResetTime} · {draft.timeZone}</dd></div><div><dt className="text-slate-500">Habits</dt><dd>{draft.tasks.length} selected</dd></div></dl></div>}
      {error&&<p role="alert" className="mt-5 rounded border border-amber-300/30 bg-amber-300/10 p-3 text-amber-100">{error}</p>}
      <div className="mt-8 flex justify-between"><button disabled={step===0||busy} onClick={()=>setStep(x=>x-1)} className="rounded border border-white/20 px-5 py-3 disabled:opacity-30">Back</button>{step<steps.length-1?<button onClick={next} className="rounded bg-cyan-300 px-6 py-3 font-semibold text-slate-950">Continue</button>:<button disabled={busy} onClick={()=>void complete()} className="rounded bg-cyan-300 px-6 py-3 font-semibold text-slate-950 disabled:opacity-50">{busy?'Creating your system…':'Create my Awaken profile'}</button>}</div>
    </div></section></main>;
}
